spring:
  application:
    name: springboot-service
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
#    console:
#      enabled: true
#      path: /h2-console
#      settings.trace: false
#      settings.web-allow-others: true
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mySqlSpringBootDb?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mySqlSpringBootDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false;MODE=MYSQL
    username: root
    password: 123
  flyway:
    enabled: true
    baselineOnMigrate: false
    validateOnMigrate: true
    locations: classpath:db/migration

app:
  authentication:
    jwtExpirationMs: 3600000
    jwtSecretKey: eyJhbGciOiJIUzI1NiJ9eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcxOTU5MTM1NiwiaWF0IjoxNzE5NTkxMzU2fQJ3qaNedZbsCT9khMJXdvgRzeXDtwca3QpzOLqhlrS6k

springdoc:
  swagger-ui:
    path: /swagger-ui

